import Link from "next/link"
import Image from "next/image"
import { SiteHeader } from "@/components/design-system/layout/SiteHeader"
import { SiteFooter } from "@/components/design-system/layout/SiteFooter"
import { Container } from "@/components/design-system/layout/Container"

export default function AboutPage() {
  return <div className="min-h-screen bg-white"><SiteHeader /><main><section className="border-b border-[var(--border)] bg-[var(--canvas-subtle)] py-14 sm:py-20"><Container><div className="grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--green-600)]">About the bureau</p><h1 className="mt-4 text-[clamp(2.7rem,5vw,4.7rem)] font-bold leading-[1.02] tracking-[-0.045em]">Healthcare expertise, shared with the community.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--text-muted)]">The Lee Health Speakers Bureau connects community organizations with healthcare professionals who can provide clear, practical education on a range of health topics.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-[var(--radius-hero-image)] border border-[var(--border)] shadow-[var(--shadow-md)]"><Image src="/hero_image.png" alt="A Lee Health speaker presenting to community members" fill className="object-cover" sizes="(min-width: 1024px) 50vw, 100vw" /></div></div></Container></section><section className="py-14 sm:py-20"><Container><div className="grid gap-8 md:grid-cols-3">{[{ title: "Browse", text: "Search speakers, seminars, and categories to find a relevant match." }, { title: "Request", text: "Share your event details through the secure public request form." }, { title: "Coordinate", text: "The outreach team confirms availability and works through the final details with you." }].map((item, index) => <article key={item.title} className="border-t-2 border-[var(--green-600)] pt-5"><p className="text-sm font-bold text-[var(--blue-600)]">0{index + 1}</p><h2 className="mt-3 text-2xl font-bold">{item.title}</h2><p className="mt-3 leading-7 text-[var(--text-muted)]">{item.text}</p></article>)}</div><div className="mt-16 flex flex-col items-start justify-between gap-6 rounded-[var(--radius-section)] bg-[var(--navy-950)] p-7 text-white sm:flex-row sm:items-center sm:p-10"><div><h2 className="text-2xl font-bold">Start with the directory</h2><p className="mt-2 text-white/75">Explore current speakers and the topics they offer.</p></div><Link href="/speakers" className="rounded-[var(--radius-button)] bg-white px-5 py-3 text-sm font-bold text-[var(--navy-950)]">Browse speakers</Link></div></Container></section></main><SiteFooter /></div>
}
